### ISSUE TITLE
Allocate time to look into how to improve our logging

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#1180]
The purpose of this story is to look into how we can improve our logging. The aim is to identify errors earlier and hopefully before actors. 

This assignment can be a team effort where we start out with a brainstorm and look into pain points or areas where we can improve logging.

**Comment by kariws** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Batman-60a6105157304f00119be86e/issues/Energinet-DataHub/geh-market-roles/1180?planning-poker) with ZenHub @CBrohus @kft @Mathiesen @Korgath
