### ISSUE TITLE
Event storming session on update customer master data

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#1181]
The purpose of this is to look into the update customer master data process and identify user stories.

**Comment by kariws** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Batman-60a6105157304f00119be86e/issues/Energinet-DataHub/geh-market-roles/1181?planning-poker) with ZenHub @CBrohus @kft @Korgath @Mathiesen
