### ISSUE TITLE
As a "user" I want to be able to view some basic information about the metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#1340]
As a user 
I want to be able to view some basic information about a metering point 
So that I have quick access to basic information

**Description**
Once a metering point has been entered into the search window, the metering point is displayed. We want to display some basic information about the metering point so the user quickly has access to some basic information. (listed in AC's)

**Acceptance criteria**
- [x] As a user I want to be able to view the status of the metering point, if it is connected, what type of metering point, type of calculation and read frequency.
![image.png](https://images.zenhubusercontent.com/60bf67953ffc7e5c3e70b6a8/1813239a-f3e8-498d-a065-15139584937b)
- [x] As a user I want to be able to view the address, if it has a energy supplier, meter number, actual address, DAR reference and comment on the metering point. 
- [x] If I mouse over the comment the comment is displayed. 
![image.png](https://images.zenhubusercontent.com/60bf67953ffc7e5c3e70b6a8/a64df804-1ae6-4405-93ce-514c553bba2a )

**Comment by Lubbe91** [comment]
DAR reference and comment on the metering point is missing UX changes right now and will stay as is until we have the correct design

![image](https://user-images.githubusercontent.com/2743537/201092899-a9f9a8ec-dd9c-44f7-aa86-b0e916da6ed5.png)
