### ISSUE TITLE
We must be able to receive calculation results from wholesale for total production so actors are able to receive the results

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-market-roles#1521]
EDI needs to be notified about the results for total production, so we know when to generate the message for the actor. 
This is a coop story between Mandalorian and Batman. The purpose is to be able to send a message to actors when a calculation has been performed and they request the message. The message will be sent in CIM-XML. 

**Acceptance criteria**

- [x] Once a calculation has been performed EDI is informed. _(Mandalorian)_ This AC is done when this issue is closed: https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/690
- [x] When a calculation for total production has been performed and a actor requests the message. A RSM-014 containing the results for total production can be peeked by the actor in the message format CIM-XML _(Batman)_

**Technical notes**
Should happen through an integration event that contains sufficient information so that the result can be identified through the wholesale API. (As agreed between architects and dev)

**Test**
When this story is complete we are able to start a batch for a specific grid and once the batch is ready we are able to peek the results and receive a RSM-014 containing total production.

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen and @Christian-Meyer, just to be clear: I understand AC2 as solely addressing MDR role and "per grid area" result.

**Comment by Christian-Meyer** [comment]
@BjarkeMeier Yes. as I understood it was only these results that where ready.
