### ISSUE TITLE
We must be able to receive a request for connection of a consumption metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#467]
As a market actor 
We want to be able to request connection of a consumption metering point
So that we can start to deliver power to the customer.

**Acceptance criteria**

- [x] We can receive a request for connect consumption metering point and
    - [x] If succesfull balance supplier receives HTTP status 200 with correlation ID
    - [x]  If unsuccesfull balance supplier receives HTTP status 400 with correlation ID
- [ ]  The solution is deployed to test

Tasks

- [ ] Create new command object for connect MP #https://github.com/Energinet-DataHub/geh-metering-point/issues/159

**Comment by Christian-Meyer** [comment]
@erduna Can we check all boxes off in this one?

**Comment by erduna** [comment]
400 is if the request is errouneus. If the request is unsuccesful (rejected), it results in a rejection message to the market actor. Everything checks out as expected :)
