### ISSUE TITLE
We must be able to subscribe to an event and listen if there has been a move in on a metering point so we can update with balance supplier

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#468]
As a system
We want to be able to subscribe to a domain
So we can receive relevant information 

**Acceptance criteria**

- [ ] We can subscribe to a servicebus 
- [ ] We can fetch relevant information about a move-in from a servicebus

Tasks

Design session #https://github.com/Energinet-DataHub/geh-metering-point/issues/157
  - Datamodel
  - Architecture consolidation
  - History

Create function that subscribes to a topic #https://github.com/Energinet-DataHub/geh-metering-point/issues/154
Create command object #https://github.com/Energinet-DataHub/geh-metering-point/issues/155
Add command object to servicebus #https://github.com/Energinet-DataHub/geh-metering-point/issues/156

**Comment by Christian-Meyer** [comment]
@kft This one has been completed by the issues #156 and #154?

**Comment by erduna** [comment]
See #262.

**Comment by erduna** [comment]
This should be in MP domain, and is solved.
