### ISSUE TITLE
We must be able to accept and reject a request for connection (includes accept and reject message generation)

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#469]
As a market actor 
We want to be able to connect a consumption metering point
So that we can start the delivery of power

**Acceptance criteria**

- [x] We can accept a request from a balance supplier
- [x] We can generate an accept message 
  - [x] Move-in is completed with todays date 
- [x] We can reject a request from a balance supplier
We can perform the following validations:
  - [x] The identification of a metering point is mandatory (rejection code E10)
  - [ ] The physical status of the metering point to which the master data applies must change from new to connected (Rejection code D16)
    - [ ] The consumption metering point with  supply obligation to which the master data information applies may only be connected if a balance supplier is registered on the effective date. (Rejection codeD36)
    - [ ] The data information must be received within the correct time frame  (rejection code E17)
- [x] We can generate a reject message

Tasks

Create command handler https://github.com/Energinet-DataHub/geh-metering-point/issues/160
Perform input validations https://github.com/Energinet-DataHub/geh-metering-point/issues/161
Create result handler https://github.com/Energinet-DataHub/geh-metering-point/issues/162
Integration event https://github.com/Energinet-DataHub/geh-metering-point/issues/163

**Comment by erduna** [comment]
Issue is in wrong repo
