### ISSUE TITLE
Meeting on integration points

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-market-roles#476]
We want to discuss and agree on the data contracts between the following domains:
 
1.	Metering point and aggregation domain
2.	Market roles and aggregation domain
 
Before the wholesale settlement process (BRS-027) can get implemented in the aggregation domain we need alignment on data contracts between the relevant domains listed above. 
 
Team Joules will create a list of expected data properties (name, data type, optional/required property) needed from both metering point and market roles domain. The list will be send out to all attendees before the meeting. 
 
Outcome of this session is agreement of data contract. Team Joules will document the data contracts.

- [x] We have agreed on data exchanged between Metering point and aggregation domain
- [x] We have agreed on data exchanged between Market roles and aggregation domain
- [ ] Data contracts are agreed upon

**Comment by Christian-Meyer** [comment]
@erduna Can we checkoff some of the boxes in this story?

**Comment by erduna** [comment]
Checked off first two. Most contracts are agreed upon, but we will revisit the mp updated event with the business to see if it can be split up or if it is good as is.

**Comment by Christian-Meyer** [comment]
Do we need to deliver more on this issue?
