### ISSUE TITLE
Move in date wrong in consumer registrations, set to 1970 by default instead of using actual movein date.

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#637]
### Current Behavior

Move in date wrong in consumer registrations, set to 1970 by default instead of using actual movein date.

### Expected behavior

Shold be null before move in date is set
Move in date should be the effectuation date.

### How to reproduce

Perform a move in.

### Environment

Dev

### Possible Solution

Use effectuation date instead.

### Additional context/screenshots

![image](https://user-images.githubusercontent.com/25637982/124931730-cb484680-e002-11eb-9a70-a7be3c72d169.png)

**Comment by Christian-Meyer** [comment]
Related to #644 queued internal command

**Comment by erduna** [comment]
The consumer registration is correctly set to null while it is not effectuated, but when effectuated it stays null. The effective date is never set.
