### ISSUE TITLE
Energy Supplier is allowed to change to himself while he's already a supplier

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#638]
### Current Behavior

Supplier is allowed to change to himself while he's already a supplier. This is relevant for change of supplier process, as the move in process should reject if you try to move in the same customer.

### Expected behavior

A supplier cannot perform a supplier change to himself while he is already the current supplier on a MP.

### How to reproduce

Perform a change of supplier on a MP where the requesting supplier is already the current supplier.

**Comment by Christian-Meyer** [comment]
Business rule
