### ISSUE TITLE
We completely ignore sender in header, we only use the sender in MktActivityRecord

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#640]
### Current Behavior

We only use the sender in the MktActivityRecord portion of the request. They need to match unless the sender in the header is allowed to send on behalf of the sender in the MktActivityRecord.

### Expected behavior

We cannot have different senders in header/payload, unless the sender in the header is allowed to send on behalf of the sender indicated in the payload (MktActivityRecord)

### How to reproduce

Send any request with different sender ids in header and payload.

**Comment by Christian-Meyer** [comment]
@cmgrd Do we do this now?
