### ISSUE TITLE
End of supply not set when a supplier loses a metering point through a move in process

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#641]
### Current Behavior

When another supplier takes over the supply for a metering point through a move in process, the previous supplier does not get an end date set for his supply period.

### Expected behavior

When another energy supplier becomes the new energy supplier of a metering point, the previous energy supplier needs an end of supply date set.

### How to reproduce

Have a supplier be active on a metering point. Effectuate another supplier on the metering point through a move in process.

### Additional context/screenshots

![image](https://user-images.githubusercontent.com/25637982/124962958-867ed880-e01f-11eb-98b6-d8f734bdbb52.png)

**Comment by Christian-Meyer** [comment]
Related to #644 queued internal command

**Comment by erduna** [comment]
Unfortunately not fixed by fixing processed date for internal commands.
