### ISSUE TITLE
Non-unique transaction id errors are not sent to market actors

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#643]
### Current Behavior

When a transaction Id is not unique, the market actor sending in the request is not informed of this through a rejection message. 

### Expected behavior

When a request fails based on a transaction Id not being unique, we need to inform the market actor of this. The current requirement from the business is:

Error Code: D02
Error Description: Identification (Inser transaction Id) not unique: transaction can not be processed for metering point (Insert metering point id)

### How to reproduce

Send in a request with a non unique Id.

**Comment by Christian-Meyer** [comment]
@Korgath @MrDach Do we handle this?

**Comment by Korgath** [comment]
@Christian-Meyer We don't handle anything regarding the transaction Id at the moment
