### ISSUE TITLE
ProcessedDate not set in outbox for actor messages nor in queuedInternalCommands

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#644]
### Current Behavior

When a request has been processed and an actor message has been sent, the message does not get a processed date set in the Outbox, nor does the command get a processed date set in the queued internal commands table.

### Expected behavior

A processed date is expected to be set when a command/message has been processed.

### How to reproduce

Send in a succesful request.

**Comment by Christian-Meyer** [comment]
When this is completed remember to close #641 and #637

**Comment by thbaan** [comment]
ActorMessageDispatcher has not yet been implemented. That´s why ProccesedDates for ActorMessages are never set.

**Comment by erduna** [comment]
Works for internal commands. 

This unfortunately does not fix various end dates not being set (eg. #641) as we suspected it might.
