### ISSUE TITLE
SSN/VAT cannot be the same as the current consumer when performing a move in

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#645]
### Current Behavior

We accept move in requests on metering points where the request contains the current consumer. This is both the case for VAT as well as private (social security number) consumers.

### Expected behavior

A current consumer cannot move in again while they are already a resident/consumer on the MP in question. If a supplier needs to be changed for the existing consumer, this can be done using the change energy supplier process.

### How to reproduce

Send a request for a metering point for the VAT/SSN number of the consumer already active on the metering point.

**Comment by Christian-Meyer** [comment]
Business rule
