### ISSUE TITLE
Consumption MP Created Event has wrong values

### ISSUE THREAD

**Issue by Korgath** [Energinet-DataHub/geh-market-roles#727]
**From Joules:**
value for NetSettlementGroup 99 is sent as an integer value of 99 instead of an int value to represent the enum specified in the contract,
value for MeterReadingPeriodicity is 2 but we only know of an enum with two options; 0 and 1)

Problem:
Protobuf Enum Id doest not match the EnumarationType Id EG:

MeteringReadingPeriodicity is 2 in MP but in the protobuf contract is 0. 

Solution:
Possible change how mapping is done.

**Comment by Korgath** [comment]
Issued confirmed.
Multiple enums comes out as integer.

**Comment by Christian-Meyer** [comment]
Permission to fix :D
