### ISSUE TITLE
Settlement method needs to be included when creating an accounting point

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#732]
### Current Behavior

Currently Settlement method is not included upon creation of an accounting point when receiving the ConsumptionMeteringPointCreated integration event.

### Expected behavior

The settlement method needs to be included when creating a corresponding accounting for a ConsumptionMeteringPointCreated  integration event. This is relevant for the following move-in rules:

![image](https://user-images.githubusercontent.com/25637982/140483016-1951c78d-a302-4671-8310-8ce087485e41.png)

### Additional context/screenshots

This can be fixed together with #722

**Comment by Christian-Meyer** [comment]
@Korgath Is this included in integration event?

**Comment by Korgath** [comment]
@Christian-Meyer  The Settlement method info is part of the consumption metering point created integration event and the new metering point created integration event.
However Market Roles does not extract that information when creating an Accounting Point

**Comment by Christian-Meyer** [comment]
@Korgath Thanks for update
