### ISSUE TITLE
MeteringPointConnected and ProductionMeteringPointCreated are not created as internal commands

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-market-roles#737]
### Current Behavior

When a MeteringPointConnected or ProductionMeteringPointCreated is sent out from the MP domain it is not created as a internal command in the MR domain. This means that the connection state is not updated in the MR domain, and that a production metering point is not created.

### How to reproduce

* Send a succesful connetion to an existing consumption metering point that also exist as an accounting point in the MR domain. The connection event is not registered in MR domain.

* Send a succesful request to create a production metering point. The event is not registered in the MR domain and no corresponding accounting point is created.

### Environment

D-002

**Comment by erduna** [comment]
![image](https://user-images.githubusercontent.com/25637982/142634557-3ce77e14-c4c0-4d11-80c0-9127649e6efe.png)
Production MP gets flagged as consumption when created as accounting point in MR

**Comment by MrDach** [comment]
@Korgath Fixed this in another task: https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/energinet-datahub/geh-metering-point/388
