### ISSUE TITLE
WithPowerLimit Null Reference Exception

### ISSUE THREAD

**Issue by MrDach** [Energinet-DataHub/geh-market-roles#870]
The error is thrown in the WithPowerLimit method that accepts string values.

It happens when trying to update PowerLimit for a MasterData object that doesn't have PowerLimit set already. 
That returns in the "GetValue" method returning null here:
```
var updatedKwh = ConvertToNullableString(kwh, GetValue<PowerLimit>(nameof(MasterData.PowerLimit)).Kwh);
var updatedAmpere = ConvertToNullableString(ampere, GetValue<PowerLimit>(nameof(MasterData.PowerLimit)).Ampere);
```

**Comment by MrDach** [comment]
Should the method be able to handle this or is it an invalid state for the MasterData object to not have PowerLimit set?

**Comment by Korgath** [comment]
@MrDach according to docs it seems to be an optional property
